name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build server
        run: cargo build --manifest-path flykeep-server/Cargo.toml

      - name: Build CLI
        run: cargo build --manifest-path flykeep-cli/Cargo.toml

      - name: Test server
        run: cargo test --manifest-path flykeep-server/Cargo.toml

      - name: Test CLI
        run: cargo test --manifest-path flykeep-cli/Cargo.toml
